In [1]:
print_imported_modules()

Module 	 Avaibility
---------------------
os         	 ✓
sys        	 ✓
glob       	 ✓
json       	 ✓
pickle     	 ✓
datetime   	 ✓
tqdm       	 ✓
copy       	 ✓
numpy      	 ✓
scipy      	 ✓
matplotlib 	 ✓
pandas     	 ✓
uproot     	 ✓

In [2]:
import strax, straxen#, cutax
straxen.print_versions()

2025-02-18 04:33:22,189 - admix - WARNING - Initializing utilix DB failed. You cannot do database operations

DB initialization failed
cutax is not installed

,module,version,path,git
0,python,3.8.13,/opt/XENONnT/anaconda/envs/XENONnT_2022.09.1/bin/python,None
1,strax,1.2.3,/opt/XENONnT/anaconda/envs/XENONnT_2022.09.1/lib/python3.8/site-packages/strax,None
2,straxen,1.8.3,/opt/XENONnT/anaconda/envs/XENONnT_2022.09.1/lib/python3.8/site-packages/straxen,None

In [3]:
st = straxen.contexts.xenonnt_online(output_folder='/project2/lgrandi/giovo/strax_data')
# st = straxen.contexts.xenonnt('global_v8', output_folder='/project2/lgrandi/giovo/strax_data')# 
# st.storage

In [5]:
selection = st.select_runs(#include_tags=('*sr1*'),
                           exclude_tags = ['flash', 'ramp_up', 'ramp_down', 'anode_off', 'abandon', 'hot_spot', 'missing_one_pmt', 'messy', 'bad']
                          )

Checking data availability:   0%|          | 0/2 [00:00<?, ?it/s]

In [8]:
time_range = ['2023-01-01', '2023-12-31']

In [9]:
selection

,name,number,mode,end,source,start,tags,livetime,peak_basics_available,raw_records_available
0,072724,72724,neutron_generator_TPC_NV_linked,NaT,neutron,2025-02-18 10:28:12.104,,NaT,False,False
1,072723,72723,mv_selftrigger,NaT,,2025-02-18 10:18:40.385,,NaT,False,False
2,072722,72722,neutron_generator_TPC_NV_linked,2025-02-18 10:27:20.544,neutron,2025-02-18 10:12:16.329,,0 days 00:15:04.215000,False,False
3,072721,72721,neutron_generator_TPC_NV_linked,2025-02-18 10:11:20.976,neutron,2025-02-18 09:56:17.883,,0 days 00:15:03.093000,False,False
4,072720,72720,neutron_generator_TPC_NV_linked,2025-02-18 09:55:25.917,neutron,2025-02-18 09:40:22.753,,0 days 00:15:03.164000,False,False
...,...,...,...,...,...,...,...,...,...,...
65547,007177,7177,xenonnt_commissioning_noise,2020-03-31 15:46:21.224,none,2020-03-31 15:45:50.914,single_copy,0 days 00:00:30.310000,False,True
65563,007161,7161,xenonnt_commissioning_noise,2020-03-19 08:44:42.178,none,2020-03-19 08:41:12.806,single_copy,0 days 00:03:29.372000,False,False
65564,007160,7160,xenonnt_commissioning_noise,2020-03-19 08:40:48.522,none,2020-03-19 08:39:17.522,single_copy,0 days 00:01:31,False,False
65565,007159,7159,xenonnt_commissioning_noise,2020-03-19 08:38:41.183,none,2020-03-19 08:37:22.348,single_copy,0 days 00:01:18.835000,False,True
65566,007158,7158,xenonnt_commissioning_noise,2020-03-18 17:42:43.982,none,2020-03-18 17:41:37.343,single_copy,0 days 00:01:06.639000,False,True

In [11]:
filtered_df = selection[(selection['start'] >= pd.to_datetime(time_range[0])) 
                        & 
                        (selection['start'] <= pd.to_datetime(time_range[1]))]
filtered_df

,name,number,mode,end,source,start,tags,livetime,peak_basics_available,raw_records_available
14837,057887,57887,background_linked,2023-12-31 02:38:14.473,none,2023-12-30 23:38:11.170,"post_maintenance,_sr2_preliminary",0 days 03:00:03.303000,False,False
14838,057886,57886,background_linked,2023-12-30 23:37:19.005,none,2023-12-30 20:37:15.728,"post_maintenance,_sr2_preliminary",0 days 03:00:03.277000,False,False
14839,057885,57885,background_linked,2023-12-30 20:36:22.967,none,2023-12-30 17:36:19.375,"post_maintenance,_sr2_preliminary",0 days 03:00:03.592000,False,False
14840,057884,57884,background_linked,2023-12-30 17:35:22.245,none,2023-12-30 14:35:18.505,"post_maintenance,_sr2_preliminary",0 days 03:00:03.740000,False,False
14841,057883,57883,background_linked,2023-12-30 14:34:26.665,none,2023-12-30 11:34:23.309,"post_maintenance,_sr2_preliminary",0 days 03:00:03.356000,False,False
...,...,...,...,...,...,...,...,...,...,...
22769,049955,49955,tpc_kr83m,2023-01-01 06:18:05.048,kr-83m,2023-01-01 05:18:02.065,,0 days 01:00:02.983000,False,False
22770,049954,49954,tpc_kr83m,2023-01-01 05:17:11.307,kr-83m,2023-01-01 04:17:08.122,,0 days 01:00:03.185000,False,False
22771,049953,49953,tpc_kr83m,2023-01-01 04:16:13.735,kr-83m,2023-01-01 03:16:10.815,,0 days 01:00:02.920000,False,False
22773,049951,49951,nVeto_self_trigger,2023-01-01 07:23:57.595,,2023-01-01 01:23:54.910,,0 days 06:00:02.685000,False,False
22774,049950,49950,mv_selftrigger,2023-01-01 07:23:45.643,,2023-01-01 01:23:42.923,,0 days 06:00:02.720000,False,False

In [ ]:
def calculate_percentage(df, plugins=['peak_basics', 'event_basics']):
    
    modes = df['mode'].unique()
    percentages = []
    
    for mode in modes:

        mode_df = df[df['mode'] == mode]
        mode_percentages = {}
        mode_percentages['Mode'] = mode
        
        for p in plugins:
            is_stored = np.array([st.is_stored(r, p) for r in mode_df['name']])
            tot_lenght = len(is_stored)
            _true = len(is_stored[is_stored==True])
            mode_percentages[f"{p}"] = f'{_true}/{tot_lenght} ({100*_true/tot_lenght}%)'
        
        percentages.append(mode_percentages)
    
    percentages_df = pd.DataFrame(percentages)
    
    return percentages_df

In [ ]:
calculate_percentage(selection)

st = cutax.contexts.xenonnt_offline(_rucio_local_path='/project/lgrandi/rucio', include_rucio_local = True, output_folder='/project2/lgrandi/giovo/strax_data')
st.storage

st.config

st.print_registered_cut_versions()

In [ ]:
selection = st.select_runs(run_mode = ('background_linked', 'background_tpc_nv', 'background_tpc_mv', 'tpc_bkg'),
                           available=('lone_hits'),
                           include_tags=('*sr2*'),
                           # exclude_tags = ('flash', 'ramp_up', 'ramp_down', 'anode_off', 'abandon', 'hot_spot', 'missing_one_pmt', 'messy', 'bad')
                          )

In [ ]:
selection.head()

In [ ]:
len(selection)

# Pymongo

In [ ]:
from utilix import xent_collection

In [ ]:
coll = xent_collection()
print(f"Connected to the database {coll.name}, with {coll.count_documents({})} documents")

In [ ]:
coll

In [ ]:
ctxs = xent_collection(collection="contexts")
for r in ctxs.find(projection={'tag': 1}):
    print(r)

In [ ]:
r

In [ ]:
query = {"number": 49918}
rd = coll.find_one(query)

# The output is a dictionary, so we can access the keys and values
for k in rd.keys():
    print(f"{k}")

In [ ]:
for d in rd['data'][:1]:
    print(f"- {d['type']}")
    print(f"    - Location: {d['location']}")
    print(f"    - Host: {d['host']}")
    print(f"    - Protocol: {d['protocol']}")
    print(f"    - Size: {d.get('size_mb', 10)} MB")
    print(f"    - File count: {d['file_count']}")
    print(f"    - Meta:")
    for k,v in d['meta'].items():
        print(f"        - {k}: {v}")

In [ ]:
print(f"- Run number: {rd['number']}")
print(f"- Start time: {rd['start']}")
print(f"- End time: {rd['end']}")
print(f"- Duration: {rd['end'] - rd['start']}")

print(f"- Mode: {rd['mode']}")
print(f"- Source: {rd['source']}")

print("- Tags:")
for t in rd['tags']:
    print(f"    {t['name']}")

print("- Comments:")
for c in rd['comments']:
    print(f"    {c['comment']}")

print("- Detectors:")
for d in rd['detectors']:
    print(f"    {d}")

print("- Rates:")
for r,v in rd['rate'].items():
    print(f"    {r:<15}: {v['avg']:.2f} ({v['max']:.2f}) MB/s")